---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: prt-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30010  # Exposing NodePort on port 30010
  type: NodePort

