---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: prt-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
      nodePort: 30010
  type: NodePort

